spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false'
    username: 'root'
    password: 'rootpassword'
    hikari:
      auto-commit: false
      connection-test-query: 'SELECT 1'
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: 'hyperuser-pool'

  data:
    redis:
      host: '127.0.0.1'
      port: 6379